project:
  type: book
  output-dir: _book

book:
  title: "Manual de Análisis Epidemiológico con R"
  author:
    - "Desarrollado por el equipo de Informática y Análisis de datos"
    - "del Instituto de Ciencias Sostenibles"
  cover-image: images/logo.png   # Si tienes un logo, si no, comenta esta línea
  chapters:
    - index.qmd
    - chapters/01-intro.qmd
    - chapters/02-fundamentos.qmd
    - chapters/03-analisis-descriptivo.qmd
    - chapters/04-analisis-epidemiologico.qmd
    - chapters/05-esquisse.qmd
    - chapters/06-visualizacion.qmd
    - chapters/07-mapas.qmd
    - chapters/08-casos-practicos.qmd

format:
  html:
    theme: cosmo
    code-fold: true
    toc: true
    lang: es
  pdf:
    documentclass: book
    papersize: letter
    toc: true
    number-sections: true
    lang: es

